package com.example.pkmail.repository;

import com.example.pkmail.entities.FcontactoSucursal2;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface FcontactoSucursal2Repository extends JpaRepository<FcontactoSucursal2,Long> {
    //enviosCliente
    @Query(value = "select Distinct su.sucursal, FC.forma_contacto, \n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 1 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Enero,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 1 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Enero_impor,\n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 2 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Febrero,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 2 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Febrero_impor, \n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 3 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Marzo,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 3 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Marzo_impor, \n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 4 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Abril,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 4 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Abril_impor, \n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 5 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Mayo,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 5 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Mayo_impor, \n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 6 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Junio,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 6 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Junio_impor, \n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 7 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Julio,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 7 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Julio_impor, \n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 8 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Agosto,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 8 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Agosto_impor, \n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 9 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Septiembre,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 9 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Septiembre_impor, \n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 10 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Octubre,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 10 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Octubre_impor, \n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 11 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Noviembre,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 11 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Noviembre_impor, \n" +
            "COALESCE((SELECT count(*) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 12 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Diciembre,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where month(STR_TO_DATE(id_fecha, \"%Y%m%d\")) = 12 AND H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Diciembre_impor,\n" +
            "COALESCE((SELECT count(*) FROM h_envios H where H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Total,\n" +
            "COALESCE((SELECT CONCAT(sum(importe)) FROM h_envios H where H.id_forma_contacto=FC.id_forma_contacto AND H.id_sucursal=su.id_sucursal AND year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))=E.anio group by FC.forma_contacto,H.id_sucursal, year(STR_TO_DATE(id_fecha, \"%Y%m%d\"))),0) Total_impor,\n" +
            "E.anio\n" +
            "from (select distinct id_forma_contacto, id_sucursal,year(STR_TO_DATE(id_fecha, \"%Y%m%d\")) anio from h_envios) E\n" +
            "Left join d_forma_contacto FC ON E.id_forma_contacto = FC.id_forma_contacto\n" +
            "Left join d_sucursal su ON E.id_sucursal = su.id_sucursal\n" +
            "where FC.forma_contacto like \"%%\" AND su.sucursal like \"%%\" AND E.anio like \"%%\"\n" +
            "group by FC.forma_contacto,su.id_sucursal,E.anio",nativeQuery = true)
    List<FcontactoSucursal2> enviosxfcontactosucursal2();
}
